[Task] Do JsDom exercise day 2
st-huunguyen/FE-Internship-Winter-2021_Huu-Nguyen-T_FE-Exercise pull request #10
Opened 2021-10-22 02:38 UTC by st-huunguyen

### Description
- [x] Hoàn thành bài tập và nộp trước 10h sáng ngày 22/10/2021

2021-10-22 11:22 UTC, st-trangnguyen requested changes
- Em chú ý các convention
- Chụp ảnh screenshot hoặc screen record kết quả bài làm gắn vào description của pull request

2021-10-22 11:22 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +  var input = document.getElementById('input');
Khi khai báo biến query dom thì đặt tên theo cú pháp `$input` hoặc `inputElm` để dễ nhận biết biến này có query tới dom nghen. Em sửa lại những chỗ khác

2021-10-22 11:22 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +    benefits.setAttribute("class", "groupBenefit");
chú ý class convention

2021-10-24 17:48 UTC, st-duynguyen commented on HTML-exercise/js-practice/domExercise.js
> +// Câu 2
Check lại css của mi, trong đề có yêu cầu đảm bảo style giống như ảnh mẫu

2021-10-24 17:48 UTC, st-duynguyen requested changes
Please check my comments

2021-10-24 18:28 UTC, st-huunguyen commented on HTML-exercise/js-practice/domExercise.js
> +// Câu 2
Đã  thêm background-color: #f7f7f7;

2021-10-24 19:41 UTC, st-trangnguyen requested changes

2021-10-24 19:41 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.css
> +.btn-secondary,
Tạo module .btn, áp dụng kiến thức đã học mọi lúc mọi nơi em

2021-10-24 19:41 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +  $input.placeholder = 'nhập năm sinh';
Tại sao ko bỏ placeholder ở html luôn nhỉ?

2021-10-24 19:41 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +var renderOption = function (options) {
renderOption => renderPlans
options => plans

2021-10-24 19:41 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +    var $listOption = document.createElement('li');
listOption => đổi tên

2021-10-24 19:41 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +    if (element.title === 'Basic') {
Tạo 1 thêm attribute trong mỗi plan gọi là type để check, để phòng tránh title nó thay đổi, hoặc nhiều plan cùng type nhưng khác title thì sao?

2021-10-24 19:41 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +    var $choiceOption = document.createElement('button');
$choiceOption ??? Tên gì đây nó chẳng thể hiện đc ý nghĩa của element gì cả

2021-10-25 02:46 UTC, st-duynguyen approved these changes
LGTM

2021-10-25 02:53 UTC, st-duynguyen commented on HTML-exercise/js-practice/domExercise.js
> +    price: '$10/month',
Tách 10 và month ra thành 2 key khác nhau

2021-10-25 05:14 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.css
> +.btn{
chú ý space, phải fix review convention hơi bị nhiều lần rồi đó Hữu hỉ

2021-10-25 05:20 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +var $listPlan = document.createElement('ul');
Đưa cái đoạn create element này vào trong hàm render plan lun em, chị ko bik bỏ ngoài này để em gì

2021-10-25 05:23 UTC, st-trangnguyen requested changes

2021-10-25 05:23 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +var $CalculateButton = document.createElement('button');
variable convention là camelCase

2021-10-25 05:23 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +var calculateAge = function () {
Đặt tên function renderCalculateAgeForm và đưa cái đoạn create element này vào trong hàm, chị ko bik bỏ ngoài này để em gì

2021-10-25 06:52 UTC, st-trangnguyen requested changes

2021-10-25 06:52 UTC, st-trangnguyen commented on HTML-exercise/js-practice/domExercise.js
> +  $CalculateButton.onclick = function (e) {
https://github.com/st-huunguyen/FE-Internship-Winter-2021_Huu-Nguyen-T_FE-Exercise/pull/10#discussion_r735264345

2021-10-27 02:31 UTC, merged