[Task] Do scss Exercise
st-huunguyen/FE-Internship-Winter-2021_Huu-Nguyen-T_FE-Exercise pull request #6
Opened 2021-10-19 02:54 UTC by st-huunguyen

### References
-[Design URL](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=0%3A1)
### Description
- [x] Tạo thư mục chứa các file scss 
- [x] chuyển code từ css sang scss

2021-10-22 02:48 UTC, st-trangnguyen requested changes
Fix conflict em nhé

2021-10-22 02:49 UTC, st-trangnguyen requested changes
label chưa đúng

2021-10-22 14:19 UTC, st-trangnguyen requested changes
- Chú ý về format file, indent, space vẫn sai nhiều
- Sử dụng nested chưa đúng
- Trong file home nên gom nhóm block css của từng theo sắp xếp từ trên xuống dưới giúp dễ quản lí code hơn

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/index.html
> +            <nav class="navigation col-xl-4">
indent chỗ này đang sai

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_all.scss
> +@import 'base';
Em chú ý sau khi tạo pull request lên github xem lại code của mình để phát hiện những lỗi đã bị review này, điển hình là ko empty line ở cuối file

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_base.scss
> +  font-size: $font-size-xs;
font-size ở html là base để tính rem, sao em lại set font-size ở đây hè?
font-size ở html đơn vị là px

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_base.scss
> +  body {
Move body ra ngoài lun em, ko cần phải nested với html mô

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_mixin.scss
> +
Thường line cuối dùng ko có space dư thừa thì nó sẽ ko hiển thị lên git, em làm sao khi push lên, line 48 ko hiển thị dấu đỏ phía sau và ko tồn tại line 49 là đc

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_reset.scss
> +*{
Phần này em move lên base

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_variable.scss
> +$color-black : #333333;
- Check space trước `:`
- Sử dụng `Maps` cho toàn bộ color ko chỉ mình gray

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_variable.scss
> +$font-size-xxxxs: 0.5rem;
Sử dụng `Maps` cho font-size

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_all.scss
> +@import 'grid';
Em phải import grid trước footer và header, phải có grid thì header và footer mới dùng grid system đc

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +  margin: 0 -0.625rem;
0.625 lặp lại nhiều lần, em taọ variable cho nó

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +.col-2 {
Dùng `for` trong sass để tính width của col

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_header.scss
> +  @extend .nav-link;
cái này ngoài kế thừa ko có thêm gì khác thì em làm như bt 
```
.nav-link,
.logo-link {
   //
}
```
Không cần phức tạp hoá lên dùng extend này nọ

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/module/_button.scss
> +      background-color: $color-primary;
indent

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_variable.scss
> +  "ab":#ababab,
Đặt tên như này khó hiểu và khó maintain quá, nếu cũng có 1 màu abacad thì như thế nào, cứ đặt theo thứ tự a-b-c-d hoặc 1-2-3-4 người sau đặt tiếp đó là đc

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_homepage.scss
> +.section-suggestions .section-header {
sao ko gộp với phía trên luôn ?

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_homepage.scss
> +.section-top-banner {
sao lại phải tách ra 2 block vậy?

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_homepage.scss
> +    @include justify-center-align-center;
@include, @extend luôn nằm đầu tiên

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_homepage.scss
> +  font-size: 4.5rem;
sử dụng font variable đã define, những chỗ khác cũng vậy

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_homepage.scss
> +.product-card .card-description {
Sao em ko dùng với block `product-card` phía trên (line 126)

2021-10-22 14:19 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_homepage.scss
> +.section-bottom-banner {
`section-bottom-banner` đang có quá nhiều block phía dưới

2021-10-22 17:27 UTC, st-huunguyen commented on HTML-exercise/stylesheets/page/_homepage.scss
> +.section-bottom-banner {
chỗ này em sửa rồi mà sao nó chưa mất review chị nè, chị xem giúp em hì.

2021-10-23 11:12 UTC, st-trangnguyen requested changes
- Còn mỗi vài lỗi nhỏ 
- UI của mobile không giống design
Em check lại mấy cái trên

2021-10-23 11:12 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_base.scss
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap");
Cái này em import ở file base/font.scss hoặc base/variable

2021-10-23 11:12 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_base.scss
> +  width: 110%;
100% thôi em, tạo sao lại cầm 110% zậy?

2021-10-23 11:12 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_footer.scss
> +  @include justify-center-align-center;
justify-center-align-center => flex-center
justify-between-align-center => flex-center-between

2021-10-23 11:12 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +.row [class*="col"] {
- Dùng nested
- Tạo biến cho .625rem

2021-10-23 11:12 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_header.scss
> +  .for-desktop {
Em đặt class theo rule `block-element-modify`
for-desktop => header-desktop
for-mobile => header-mobile

2021-10-23 11:12 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_header.scss
> +  nav {
Dùng class

2021-10-23 11:12 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_all.scss
> +@import 'homepage'
homepage => home-page

2021-10-23 12:04 UTC, st-huunguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +.row [class*="col"] {
trong file này em dùng một lần là .625rem và một lần là -.625rem mà cũng phải tạo biến hả chị :3

2021-10-23 12:41 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +.row [class*="col"] {
a với -a thì đã dùng lại a rồi mà em???
với lại nó có thể thay đổi a theo breakpoint nữa

2021-10-23 13:03 UTC, st-huunguyen commented on HTML-exercise/stylesheets/base/_base.scss
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap");
em chuyển qua base/variable  rồi á chị mà sao commet này chưa mất nữa

2021-10-23 13:10 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/base/_base.scss
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap");
chuyển qua rồi mà ko xoá ở đây đi ông

2021-10-23 14:07 UTC, st-trangnguyen requested changes
Hoàn toàn ko giống design. Nếu vào dự án khác hàng đưa design cho mình 1 trời mà mình làm ra 1 vực thì hậu quả sẽ như thế nào???
![Screen Shot 2021-10-23 at 20 22 40](https://user-images.githubusercontent.com/63229420/138559881-d0308de7-ffc3-4b79-9860-df4c34079af5.png)
![Screen Shot 2021-10-23 at 20 22 18](https://user-images.githubusercontent.com/63229420/138559887-ab474970-36aa-4a47-b6bd-38ab71f4753c.png)
![Screen Shot 2021-10-23 at 20 20 53](https://user-images.githubusercontent.com/63229420/138559889-1a12d21d-6694-408e-8f16-ac7aeb50fed4.png)
![Screen Shot 2021-10-23 at 20 20 35](https://user-images.githubusercontent.com/63229420/138559890-eb2a06cf-1bb9-46fb-acee-0d6554da6495.png)
![Screen Shot 2021-10-23 at 20 20 13](https://user-images.githubusercontent.com/63229420/138559892-95ab50b8-a30a-41cd-ae30-b89fd5322e0b.png)
![Screen Shot 2021-10-23 at 20 20 04](https://user-images.githubusercontent.com/63229420/138559894-c6784ab4-4a42-43f2-a3a7-32c2d4931038.png)
![Screen Shot 2021-10-23 at 20 19 56](https://user-images.githubusercontent.com/63229420/138559895-a00335ed-a74d-483b-bc3c-94c381b1f90d.png)

2021-10-23 14:07 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +  margin: 0 -(map-get($font-size, "xxxs" ));
Em define variable riêng cho cái padding margin ở đây, nếu sau này font-size thì thay đổi mà space ở đây vẫn giữ nguyên thì như thế nào?
Và font-size là font-size, space là space

2021-10-23 14:07 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +    .col{
Viết như vào là col sẽ là con của col?

2021-10-23 14:07 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +@for $i from 1 through 12 {
Viết mixin cho 2 vòng for bị lặp này để optimize code

2021-10-23 14:07 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/module/_card.scss
> +    @include font-size-weight(map-get($font-size,"m"), 300);
chú ý space sau `,` trong map-get. Tương tự những chỗ khác

2021-10-23 14:07 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/module/_card.scss
> +    color: map-get($color, "black" );
Dư space trước `)`

2021-10-23 14:07 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/page/_home-page.scss
> +        @include font-size-weight(map-get($font-size, "xxl"), 400);
@include, @extend luôn phài nằm lên đầu tiên

2021-10-23 16:48 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/module/_list.scss
> +.list-group {
.list-group,
.list-item {
  @include flex-center-between;
  list-style-type: none;
}
cho nhanh chứ cần gì extend khổ vậy em, em dùng extend cho những trường hợp này ko đúng

2021-10-23 16:49 UTC, st-huunguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +@for $i from 1 through 12 {
đoạn này em làm ko có ra chị ơi :(((
Chị bày em đoạn này đi <3

2021-10-23 16:53 UTC, st-trangnguyen commented on HTML-exercise/stylesheets/layout/_grid.scss
> +@for $i from 1 through 12 {
```
// Mixins for build grid
$grid-columns: 12;
@mixin build-grid($size) {
  @for $i from 1 through $grid-columns {
    @if $size != "" {
      .col-#{$size}-#{$i} {
        flex: 0 0 percentage($i / $grid-columns);
        max-width: percentage($i / $grid-columns);
      }
    } @else {
      .col-#{$i} {
        flex: 0 0 percentage($i / $grid-columns);
        max-width: percentage($i / $grid-columns);
      }
    }
  }
}
```

2021-10-23 16:55 UTC, st-trangnguyen reviewed
Chị merge pull này, tuy nhiên còn nhiều cái cần tìm hiểu và khắc phục, tiến bộ hơn trong những lần làm UI tiếp theo. 
- Always làm đúng theo design
- Chú ý về convention
- Tìm hiểm thêm về sass để sử dụng hết tính năng của nó

Thankiu em.

2021-10-23 16:56 UTC, merged