[Task] Do JavaScript playground and  homework on first day
st-huunguyen/FE-Internship-Winter-2021_Huu-Nguyen-T_FE-Exercise pull request #9
Opened 2021-10-20 17:51 UTC by st-huunguyen

### Description
- [x] làm bài tập phần playground và homework, nộp trước 10h sáng ngày 21/10/2021

2021-10-20 18:12 UTC, st-duynguyen commented on HTML-exercise/js-practice/homework.js
> +var capitalize = function (string) {
Hàm này đặt tên thiêys ý? Viết Hoa cả đoạn text hay chữ cái đầu câu?

2021-10-20 18:14 UTC, st-duynguyen commented on HTML-exercise/js-practice/homework.js
> +  output = string[0].toUpperCase().concat(string.slice(1, string.length));
Rút gọn chỉ cần output = string[0].toUpperCase().concat(string.slice(1));

2021-10-20 18:22 UTC, st-duynguyen commented on HTML-exercise/js-practice/homework.js
> +var totalDigit = function (number) {
đặt tên hàm là động từ

2021-10-20 18:23 UTC, st-duynguyen commented on HTML-exercise/js-practice/homework.js
> +};
check 1 dòng trống cuối bài

2021-10-20 18:25 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +  } else {
chỗ này k cần else đâu, return thẳng về lun

2021-10-20 18:26 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +var getSum = function (number1, number2) {
tên hàm chưa handle được hết tất cả các case của funtion này

2021-10-20 18:26 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +var calculateDifference = function (number) {
Tên hàm này cũng vậy

2021-10-20 18:26 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +  } else return 19 - number;
tương tự k cần else chỗ này, return về thẳng lun

2021-10-20 18:27 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +  } else {
hàm này k cần else ở đây, cứ viết hàm for ở dưới bt

2021-10-20 18:33 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +  var input = divisibleBy3(input);
2 bài tập riêng biệt, k nên dùng lại bài tập trên, viết riêng ra đi

2021-10-20 18:33 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +};
check empty line cuối bài

2021-10-20 18:37 UTC, st-duynguyen commented on HTML-exercise/js-practice/playground.js
> +      parseInt(change);
phải gán lại charge = parseInt(charge)

2021-10-20 18:42 UTC, st-duynguyen requested changes
Pls check my comments

2021-10-21 09:01 UTC, st-trangnguyen requested changes

2021-10-21 09:01 UTC, st-trangnguyen commented on HTML-exercise/js-practice/homework.js
> +var cutString = function (string) {
```
var cutString = function (string) {
  if (string && string.length > 15) {
    string = string.slice(0, 10).concat("...");
  }
  return string;
};
```
- Ngắn gọn ko nè :)))
- Em nên kiểm tra thêm param vào có bị null ko nhé, null.length sẽ bị lỗi dễ gây ra trắng app

2021-10-21 09:01 UTC, st-trangnguyen commented on HTML-exercise/js-practice/playground.js
> +    return number1 + number2;
Chú ý indent em nhé

2021-10-21 09:01 UTC, st-trangnguyen commented on HTML-exercise/js-practice/playground.js
> +    change=parseInt(change);
chú ý thêm space `change = parseInt(change);`

2021-10-21 09:01 UTC, st-trangnguyen commented on HTML-exercise/js-practice/homework.js
> +  var array = [
Bài tập này em sửa lại nhận vào param là 1 array thay vì force array ở trong hàm

2021-10-21 09:01 UTC, st-trangnguyen commented on HTML-exercise/js-practice/homework.js
> +  var output = "";
Hạn chế tạo thêm biến nếu ko cần thiết em, cứ lấy param mà sử dụng lun

2021-10-22 04:38 UTC, st-duynguyen commented on HTML-exercise/js-practice/homework.js
> +  string.toLowerCase();
Biết là đúng nhưng sẽ k ai chơi kiểu này. string = string.toLowerCase();

2021-10-22 10:20 UTC, st-duynguyen commented
@st-huunguyen Cần check lại cẩn thận đã fix hết comments chưa trước khi chuyển label nghe. Phải check lại cẩn thận PR của mình trước khi assign cho người khác hoặc chuyển label

2021-10-22 11:12 UTC, st-trangnguyen requested changes
Em check fix tất cả comment và sửa lại trong file JS phải dùng `''` thay vì `""`, đó là convention của team

2021-10-24 15:05 UTC, st-duynguyen approved these changes
LGTM

2021-10-24 15:44 UTC, merged